### ISSUE TITLE
Failed to import project Maven dependency

### ISSUE THREAD

**Issue by Languomao** [apache/submarine#202] opened 2020-03-04 02:30 UTC
When I introduced Maven dependencies for a project, the following error occurred:

`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:56 min
[INFO] Finished at: 2020-03-04T01:34:24Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project submarine-client: Could not resolve dependencies for project org.apache.submarine:submarine-client:jar:0.4.0-SNAPSHOT: Failed to collect dependencies at org.apache.submarine:commons-runtime:jar:0.4.0-SNAPSHOT: Failed to read artifact descriptor for org.apache.submarine:commons-runtime:jar:0.4.0-SNAPSHOT: Could not transfer artifact org.apache.submarine:commons-runtime:pom:0.4.0-SNAPSHOT from/to apache.snapshots (http://repository.apache.org/snapshots): Connect to repository.apache.org:80 [repository.apache.org/207.244.88.140] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

How can we introduce the necessary dependency correctly? Or which online warehouse to use?
Looking forward to your answer，Thanks a lot!

**Comment by liuxunorg** [comment] 2020-03-04 02:48
hi @Languomao :-)
You are welcome to use submarine, you can compile subamrine according to this document. https://github.com/apache/submarine/blob/master/docs/development/BuildFromCode.md

I think this command should solve your problem: 
```
mvn clean install package -DskipTests -Phadoop-2.9
```

**Comment by Languomao** [comment] 2020-03-08 09:25
> hi @Languomao :-)
> You are welcome to use submarine, you can compile subamrine according to this document. https://github.com/apache/submarine/blob/master/docs/development/BuildFromCode.md
> 
> I think this command should solve your problem:
> 
> ```
> mvn clean install package -DskipTests -Phadoop-2.9
> ```
When I import dependency, it will prompt

`Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/apache/submarine/commons-runtime/0.4.0-SNAPSHOT/maven-metadata.xml`

But the download failed, when I go to http://repository.apache.org/snapshots/org/apache/submarine/commons-runtime/0.4.0-snapshot/ to view this path, this path does not exist, and then I switch to http://repository.apache.org/snapshots/org/apache/submarine/commons-runtime/0.3.0-snapshot/ ，but under this path, the file maven-metadata.xml does not exist。
Where can I find this file，thanks a lot。

**Comment by liuxunorg** [comment] 2020-03-08 09:39
mvn install will compile submarine locally and install it into your local mvn repository. Not downloaded from Apache's mvn repository.
If you cannot compile by executing `mvn clean install package -DskipTests -Phadoop-2.9`, i think, it should be caused by network problems.

**Comment by jojochuang** [comment] 2020-03-17 13:08
Feel free to use users@submarine.apache.org too: https://submarine.apache.org/community/contributors.html

**Comment by jojochuang** [comment] 2020-04-03 19:43
I have no problem downloading from repository.apache.org. Inclined to believe this is network issue. @Languomao let me know if there's still issue otherwise I'll close this issue.

**Comment by jiwq** [comment] 2020-08-27 06:07
Close this issue, if the problem is still exist, free to reopen. @Languomao

**Closed by jiwq** 2020-08-27 06:07 UTC
